diag_log ("Loading Structures");
#include"\z\addons\dayz_server\buildings\nw_na_wrecks_c130.sqf";
#include"\z\addons\dayz_server\buildings\infinicity.sqf";
#include"\z\addons\dayz_server\buildings\billboards.sqf";
#include "\z\addons\dayz_server\buildings\ch_train_wreck.sqf";
#include "\z\addons\dayz_server\buildings\ss_military_complex.sqf";
#include "\z\addons\dayz_server\buildings\ch_sawmill.sqf";
#include "\z\addons\dayz_server\buildings\zg_complex.sqf";
#include "\z\addons\dayz_server\buildings\ne_airfield.sqf";
#include"\z\addons\dayz_server\buildings\gm_military_complex.sqf";
#include"\z\addons\dayz_server\buildings\si_castle.sqf";
#include"\z\addons\dayz_server\buildings\misc.sqf";
#include"\z\addons\dayz_server\buildings\furniture_houseV2_02.sqf";
#include"\z\addons\dayz_server\buildings\tikhaya_bay.sqf";
#include"\z\addons\dayz_server\buildings\wip_lopatino.sqf";
#include"\z\addons\dayz_server\buildings\vaults.sqf";
#include"\z\addons\dayz_server\buildings\furniture_land_mil_house.sqf";
#include"\z\addons\dayz_server\buildings\furniture_land_mil_guardhouse.sqf";
#include"\z\addons\dayz_server\buildings\furniture_land_mil_barracks.sqf";
#include"\z\addons\dayz_server\buildings\wildzeds.sqf";
diag_log ("Loading Structures - Complete!");